# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: GitHub Pages Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - uses: r-lib/actions/setup-pandoc@v1
      with:
        pandoc-version: 2.9.2.1
    - name: Install texlive 
      run: sudo apt install -y texlive texlive-xetex
    - name: Install source-serif
      run: |
        wget https://github.com/adobe-fonts/source-serif/releases/download/4.004R/source-serif-4.004.zip
        unzip source-serif-4.004.zip -d /usr/share/fonts/
        wget https://github.com/adobe-fonts/source-han-serif/releases/download/2.000R/SourceHanSerif.ttc.zip
        unzip SourceHanSerif.ttc.zip -d /usr/share/fonts/
        fc-cache
    - run: yarn install && yarn workspace tuesday build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./tuesday/public
        cname: tuesday.dontpanic.blog
        commit_message: ${{ github.event.head_commit.message }}
        
